# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_sign', '0002_bodysignal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodysignal',
            name='is_critical',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
