# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('body_sign', '0005_auto_20170515_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellChair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellchair', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
