# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiss_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=1, editable=False, max_length=512),
            preserve_default=False,
        ),
    ]
