# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiss_auth', '0005_auto_20170515_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='monitoruser',
            name='android_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
