# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-24 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umiss_auth', '0007_auto_20170524_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='monitor_users',
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='monitors',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
