# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiss_auth', '0008_auto_20170524_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
