# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiss_auth', '0009_monitor_is_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='is_logged',
            field=models.CharField(default='false', max_length=20),
        ),
    ]
